variables:
  GIT_SUBMODULE_STRATEGY: recursive
stages:
  - deploy staging
  - deploy

deploy staging:
  image: node:latest
  stage: deploy staging
  script:
    - npm i -g serverless
    - npm i
    - serverless config credentials --provider aws --key $ACCESS_KEY --secret $SECRET_KEY
    - serverless deploy --stage dev
  only:
    - master
deploy:
  image: node:latest
  stage: deploy staging
  script:
    - npm i -g serverless
    - npm i
    - serverless config credentials --provider aws --key $ACCESS_KEY --secret $SECRET_KEY
    - serverless deploy --stage prod
  only:
    - tags
