service: bibserver
provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-west-1
  memorySize: 384
functions:
  app:
    handler: dist/index.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

