name: publish bibserver

on:
  push:
    branches:
    - master    

jobs:
  publish-bibserver-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the android-sdk-azure-devops-agent Docker image
      run: |
        docker build . --tag ghcr.io/jamescoverdale/bibserver:latest        
        docker push ghcr.io/jamescoverdale/bibserver:latest
